<?php

namespace ColorAnomaly;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-09 at 20:31:25.
 */
class VinesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Vines
     */
    protected $o;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $config = nestConfig(cascadeConfig(APPLICATION_ENV, parse_ini_file(APPLICATION_PATH . '/config/settings.ini', true)));

        $this->o = new Vines($config['app']['db']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->o->purgeDatabase();
    }

    public function testAccessGrantedWhenPermitted() {
        $this->o->addAction('enter', '');

        $this->o->addRole('principal');
        $this->o->addRole('teacher');
        $this->o->addRole('student');

        $this->o->addResource('school', Vines::TREE_ROOT_ALIAS);
        $this->o->addResource('north-wing', 'school');
        $this->o->addResource('south-wing', 'school');
        $this->o->addResource('class1', 'north-wing');
        $this->o->addResource('class2', 'south-wing');
        $this->o->addResource('class3', 'south-wing');
        $this->o->addResource('office', 'school');
        $this->o->addResource('principal-office', 'office');

        $this->o->enforce(true, 'enter', 'teacher', 'south-wing');
        $this->o->enforce(true, 'enter', 'student', 'north-wing');

        $this->assertFalse($this->o->allowed('teacher', 'enter', 'class1'));
        $this->assertTrue($this->o->allowed('teacher', 'enter', 'class2'));
        $this->assertTrue($this->o->allowed('teacher', 'enter', 'class3'));
        $this->assertTrue($this->o->allowed('student', 'enter', 'class1'));
    }

}
