<?php

namespace ColorAnomaly;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-09 at 20:31:25.
 */
class VinesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Vines
     */
    protected $o;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $config = nestConfig(cascadeConfig(APPLICATION_ENV, parse_ini_file(APPLICATION_PATH . '/config/settings.ini', true)));
        
        $this->o = new Vines($config['app']['db']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->o->purgeDatabase();
    }
    
    public function testAccessGrantedWhenPermitted() {
        $this->o->addAction('enter', '');
        
        $this->o->addRole('principal');
        $this->o->addRole('teacher');
        $this->o->addRole('student');
        
        $this->o->addResource('school', Vines::TREE_ROOT_ALIAS);
        $this->o->addResource('north-wing', 'school');
        $this->o->addResource('south-wing', 'school');
        $this->o->addResource('class1', 'north-wing');
        $this->o->addResource('class2', 'south-wing');
        $this->o->addResource('class3', 'south-wing');
        $this->o->addResource('office', 'school');
        $this->o->addResource('principal-office', 'office');
        
        $this->o->enforce(true, 'enter', 'teacher', 'south-wing');
        $this->o->enforce(true, 'enter', 'student', 'north-wing');
        
        $this->assertFalse($this->o->allowed('teacher', 'enter', 'class1'));
        $this->assertTrue($this->o->allowed('teacher', 'enter', 'class2'));
        $this->assertTrue($this->o->allowed('teacher', 'enter', 'class3'));
        $this->assertTrue($this->o->allowed('student', 'enter', 'class1'));
    }

    /**
     * @covers ColorAnomaly\Vines::checkTreeStructure
     * @todo   Implement testCheckTreeStructure().
     */
    public function testCheckTreeStructure() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion() {
        $this->assertEquals('1.0.0', $this->o->getVersion());
    }

    /**
     * @covers ColorAnomaly\Vines::addTreeNode
     * @todo   Implement testAddTreeNode().
     */
    public function testAddTreeNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::removeTreeNode
     * @todo   Implement testRemoveTreeNode().
     */
    public function testRemoveTreeNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::addResource
     * @todo   Implement testAddResource().
     */
    public function testAddResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::removeResource
     * @todo   Implement testRemoveResource().
     */
    public function testRemoveResource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::addTag
     * @todo   Implement testAddTag().
     */
    public function testAddTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::removeTag
     * @todo   Implement testRemoveTag().
     */
    public function testRemoveTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::tagRole
     * @todo   Implement testTagRole().
     */
    public function testTagRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::untagRole
     * @todo   Implement testUntagRole().
     */
    public function testUntagRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::addRole
     * @todo   Implement testAddRole().
     */
    public function testAddRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::removeRole
     * @todo   Implement testRemoveRole().
     */
    public function testRemoveRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::addAction
     * @todo   Implement testAddAction().
     */
    public function testAddAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::editAction
     * @todo   Implement testEditAction().
     */
    public function testEditAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::removeAction
     * @todo   Implement testRemoveAction().
     */
    public function testRemoveAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::enforce
     * @todo   Implement testEnforce().
     */
    public function testEnforce() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::enforceTag
     * @todo   Implement testEnforceTag().
     */
    public function testEnforceTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::allowed
     * @todo   Implement testAllowed().
     */
    public function testAllowed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ColorAnomaly\Vines::purgeDatabase
     * @todo   Implement testPurgeDatabase().
     */
    public function testPurgeDatabase() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
