DROP TABLE IF EXISTS `control`;
DROP TABLE IF EXISTS `tcontrol`;
DROP TABLE IF EXISTS `role_tag`;
DROP TABLE IF EXISTS `action`;
DROP TABLE IF EXISTS `resource`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `tag`;